####################################################################
# !!! REMINDER !!!                                                 #
# Don't forget to run `manala up` each time you update this file ! #
####################################################################

manala:
    recipe: ops.cd
    repository: /Users/loic/Ops/manala-recipes

# Default vars
semantic_release:
    exec: { publishCmd: npm run build }
    github: 
        assets:
            - { path: ./build/*.js } 
            - { path: ./build/*.js.app }
