####################################################################
# !!! REMINDER !!!                                                 #
# Don't forget to run `manala up` each time you update this file ! #
####################################################################

manala:
    recipe: dev.jxa
    repository: /Users/loic/Ops/manala-recipes

# Default vars
semantic_release:
    exec: 
        publishCmd: npm run package
    github: 
        assets: [{ path: ./build }, { path: ./assets }]
